title: 'K Perham'
name: 'K Perham'
url: https://kmp24.github.io/new-portfolio
repository: 'https://kmp24.github.io/new-portfolio'
include:
    - _pages
    - assets
    - index.html
exclude:
    - TODO.md
    - README.md
    - '*.org'
    - '*ltximg*'
plugins:
    - jekyll-feed
    - jekyll-remote-theme
    - jekyll-include-cache
markdown: kramdown
#theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dirt
author:
    name: 'Kaitlyn Perham'
    avatar: /assets/images/wmnf.jpg
    location: 'New Hampshire'
    github: kmp24
    linkedin: kaitlyn-perham
analytics:
    provider: "google"
    google:
        tracking_id: "UA-105425818-1"
paginate: 10
paginate_path: '/page:num/'
defaults:
    -
        scope:
            path: ""
        values:
            layout: single
            mathjax: true
            author_profile: true
            class: wide
            title: ' '
            title_separator: '|'
    -
        scope:
            type: posts
        values:
            toc: true
            toc_label: Contents
            read_time: false
            comments: true
    -
        scope:
            path: ""
            type: portfolio
        values:
            author_profile: false
            excerpt: ""
            sidebar: {nav: portfolio}
collections:
    portfolio:
        output: true
